export interface Game {
    company: string;
    date: string;
    name: string;
    genre: string;
    img: string;
    status: 'inactive' | 'progress' | 'complete';
}

export const games = [
    {
        company: 'SystemSoft',
        date: '10/30/1983',
        name: 'Lode Runner',
        genre: 'Puzzle Platform',
        img: 'loderunner.png',
        status: 'inactive',
    },
    {
        company: 'Enix / Chunsoft',
        date: '1/1/1984',
        name: 'Door Door',
        genre: 'Puzzle Platform',
        img: 'door.png',
        status: 'inactive',
    },
    {
        company: 'System Sacom',
        date: '8/1/1985',
        name: 'Marchen Veil',
        genre: 'Action Adventure',
        img: 'marchen.png',
        status: 'inactive',
    },
    {
        company: 'System Sacom',
        date: '6/14/1986',
        name: 'Marchen Veil II',
        genre: 'Top-Down Action',
        img: 'marchen2.png',
        status: 'inactive',
    },
    {
        company: 'Humming Bird Soft',
        date: '1/1/1987',
        name: 'Laplace no Ma',
        genre: 'Horror JRPG',
        img: 'laplacenoma.png',
        status: 'inactive',
    },
    {
        company: 'Pony Canyon',
        date: '12/5/1987',
        name: 'Little Computer People',
        genre: 'Human Sim',
        img: 'littlecomputer.png',
        status: 'inactive',
    },
    {
        company: 'Victor Musical Industries, Inc.',
        date: '1/1/1988',
        name: 'Atlantia',
        genre: 'Run N Gun',
        img: 'atlantia.png',
        status: 'inactive',
    },
    {
        company: 'Micro Cabin',
        date: '6/1/1989',
        name: 'Xak',
        genre: 'Action RPG',
        img: 'xak.png',
        status: 'inactive',
    },
    {
        company: 'Technical Group Laboratory, Inc.',
        date: '1/15/1993',
        name: 'Edge',
        genre: 'Beat Em Up',
        img: 'edge.jpg',
        status: 'inactive',
    },
    {
        company: 'FairyTale',
        date: '9/21/1990',
        name: 'X・na',
        genre: 'Dungeon Crawler',
        img: 'xna.png',
        status: 'inactive',
    },
    {
        company: 'Micro Cabin',
        date: '1/1/1990',
        name: 'Xak II',
        genre: 'Fantasy RPG',
        img: 'xak2.png',
        status: 'inactive',
    },
    {
        company: 'Micro Cabin',
        date: '1/1/1991',
        name: 'Fray in Magical Adventure',
        genre: 'Shoot Em Up',
        img: 'fray.png',
        status: 'inactive',
    },
    {
        company: 'Studio Brown Rice',
        date: '1/1/1992',
        name: 'Steel Gun Nyan',
        genre: 'Lightgun Shooter',
        img: 'steelgun.png',
        status: 'inactive',
    },
    {
        company: 'Micro Cabin',
        date: '1/1/1992',
        name: 'Elm Knight',
        genre: 'FPS',
        img: 'elm.png',
        status: 'inactive',
    },
    {
        company: 'KUNI Soft',
        date: '1/1/1992',
        name: 'Mobile Delivery',
        genre: '3D Racer',
        img: 'mobiledelivery.png',
        status: 'inactive',
    },
    {
        company: 'Taito',
        date: '5/25/1990',
        name: 'Puzznic',
        genre: 'Tile Puzzler',
        img: 'pizz.jpg',
        status: 'inactive',
    },
    {
        company: 'TGL',
        date: '3/25/1992',
        name: 'Sword Dancer',
        genre: 'Fighting RPG',
        img: 'sworddancer.png',
        status: 'inactive',
    },
    {
        company: 'FairyTale',
        date: '5/15/1992',
        name: 'Dead of the Brain',
        genre: 'Adventure Horror',
        img: 'dead1.png',
        status: 'inactive',
    },
    {
        company: 'Birdy Soft',
        date: '9/10/1992',
        name: 'My Eyes!',
        genre: 'Marine Adventure',
        img: 'my eyes.png',
        status: 'inactive',
    },
    {
        company: 'Tokyo Shoseki Co., Ltd.',
        date: '11/6/1992',
        name: 'Ugetsu Kitan',
        genre: 'Visual Novel',
        img: 'uget.png',
        status: 'inactive',
    },
    {
        company: 'Chime',
        date: '12/4/1992',
        name: 'Earth Defense Girl Iko UFO',
        genre: 'Card Adventure',
        img: 'ufo.png',
        status: 'inactive',
    },
    {
        company: 'Onion Soft',
        date: '1/1/1993',
        name: 'Cattle Mutilation',
        genre: 'UFO Action',
        img: 'cattle.png',
        status: 'inactive',
    },
    {
        company: 'Matrix',
        date: '1/1/1993',
        name: 'KO Seiki Beast Sanjuushi',
        genre: 'RPG Lite',
        img: 'kobeast.png',
        status: 'inactive',
    },
    {
        company: 'Studio K2',
        date: '1/1/1993',
        name: 'Case of Dungeons',
        genre: 'Isometric RPG',
        img: 'case.png',
        status: 'inactive',
    },
    {
        company: 'Micro Cabin',
        date: '4/23/1993',
        name: 'Xak III',
        genre: 'Action RPG',
        img: 'xak3.png',
        status: 'inactive',
    },
    {
        company: 'NEC',
        date: '6/25/1993',
        name: 'Tanjo Debut',
        genre: 'Idol Sim',
        img: 'tanjo.png',
        status: 'inactive',
    },
    {
        company: 'C-Lab',
        date: '6/1/1993',
        name: 'Rusty',
        genre: 'Adventure of Linkvania',
        img: 'rusty.png',
        status: 'inactive',
    },
    {
        company: 'Nihon Bisson',
        date: '6/30/1993',
        name: 'Mahjong Triple Wars Gaiden',
        genre: 'Mahjong RPG',
        img: 'mahjongtriple.png',
        status: 'inactive',
    },
    {
        company: 'FairyTale',
        date: '11/26/1993',
        name: 'Dead of the Brain 2',
        genre: 'Adventure Horror',
        img: 'dead2.png',
        status: 'inactive',
    },
    {
        company: 'Maxima',
        date: '1/1/1990',
        name: 'Zark Legend Special',
        genre: 'Action Platformer',
        img: 'zark.jpg',
        status: 'inactive',
    },
    {
        company: 'Compile',
        date: '5/5/1996',
        name: 'Compile Disc Station Vol.10',
        genre: 'Digital Magazine',
        img: 'ds10.jpg',
        status: 'inactive',
    },
    {
        company: 'TGL',
        date: '5/26/1994',
        name: 'Sword Dancer 2',
        genre: 'Fighting RPG',
        img: 'sword2.png',
        status: 'inactive',
    },
    {
        company: 'C-lab.',
        date: '6/17/1994',
        name: 'Totsugeki Mix!',
        genre: 'Action Platformer',
        img: 'totsugeki.png',
        status: 'inactive',
    },
    {
        company: 'Konami',
        date: '6/29/1994',
        name: 'Policenauts',
        genre: 'Sci-Fi Adventure',
        img: 'polcenauts.png',
        status: 'inactive',
    },
    {
        company: 'KSS',
        date: '9/22/1994',
        name: 'Idol Project',
        genre: 'Idol Sim',
        img: 'ip1.png',
        status: 'inactive',
    },
    {
        company: 'Compile',
        date: '10/7/1994',
        name: 'Compile Disc Station Vol. 4',
        genre: 'Digital Magazine',
        img: 'ds4.png',
        status: 'inactive',
    },
    {
        company: 'Starcraft',
        date: '11/11/1994',
        name: 'Rhyme Star',
        genre: 'Board Battler',
        img: 'rhyme.png',
        status: 'inactive',
    },
    {
        company: 'Compile',
        date: '1/9/1995',
        name: 'Compile Disc Station Vol.5',
        genre: 'Digital Magazine',
        img: 'ds5.png',
        status: 'inactive',
    },
    {
        company: 'Compile',
        date: '4/7/1995',
        name: 'Compile Disc Station Vol.6',
        genre: 'Digital Magazine',
        img: 'ds6.png',
        status: 'inactive',
    },
    {
        company: 'Compile',
        date: '7/7/1995',
        name: 'Compile Disc Station Vol.7',
        genre: 'Digital Magazine',
        img: 'ds7.png',
        status: 'inactive',
    },
    {
        company: 'KSS',
        date: '12/22/1995',
        name: 'Idol Project 2',
        genre: 'Idol Sim',
        img: 'ip2.png',
        status: 'inactive',
    },
    {
        company: 'Comrade Systems',
        date: '1/1/1996',
        name: 'Brah',
        genre: 'post-apocalyptic RPG',
        img: 'brah.png',
        status: 'inactive',
    },
    {
        company: 'SystemSoft',
        date: '2/23/1996',
        name: 'Tuned Heart',
        genre: 'Cop RPG',
        img: 'tunedheart.png',
        status: 'inactive',
    },
    {
        company: 'Cosmos Computer',
        date: '12/14/1993',
        name: 'Magic++',
        genre: 'Action Adventure',
        img: 'magic.png',
        status: 'inactive',
    },
    {
        company: 'Cocktail Soft',
        date: '7/26/1996',
        name: 'Pia Carrot',
        genre: 'Dating Sim',
        img: 'piacarrot.png',
        status: 'inactive',
    },
    {
        company: 'Glodia',
        date: '11/5/1993',
        name: 'Alvaleak Bōkenki',
        genre: 'Dungeon Crawler',
        img: 'alva.jpg',
        status: 'inactive',
    },
    {
        company: 'Sunsoft',
        date: '5/16/1997',
        name: 'Photo Genic',
        genre: 'Dating Sim',
        img: 'photo.png',
        status: 'inactive',
    },
    {
        company: 'TKO Soft',
        date: '6/13/1997',
        name: 'Yuugekitai',
        genre: 'Humor Adventure',
        img: 'yuug.png',
        status: 'inactive',
    },
    {
        company: 'Sogna',
        date: '4/3/1998',
        name: 'Guynarock R',
        genre: 'Space Adventure',
        img: 'guyna.png',
        status: 'inactive',
    },
    {
        company: 'Makoto Serise',
        date: '5/31/1998',
        name: 'Peret em Heru',
        genre: 'Horror RPG',
        img: 'peret.png',
        status: 'inactive',
    },
] as Game[];
